name: Example workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build and Test
      run: echo "Building and testing..."

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-file
        path: ./my-file.txt

    - name: Manual Approval
      if: github.event_name == 'push'
      uses: trstringer/manual-approval@v1
      with:
        message: 'Please approve the deployment'
        reviewers: 'steja6872'
        file-content: ${{ steps.UploadArtifact.outputs.my-file.txt }}
